#!/bin/bash

# 引数を変数に格納
arg1=$1
arg2=$2

# 引数の確認
if [ -z "$arg1" ] || [ -z "$arg2" ]; then
        echo "引数がたりない"
        exit 0
fi

# gitコマンドの実行
git add "$arg1"
git commit -m "$arg2"
git push origin master
